# 1. DataLab (aka Jupyter Notebook)

Welcome to Google Cloud DataLab - Web Application based on Open Source project 'Jupyter Notebook' used to manage so called iPython Notebooks which combines static document and Python runtime, that can contain your python scripts, the results of their execution, description fo your code, plots, tables and many, many more. Saved Notebooks can be easily shared with other developers you work with or hosted publicly, e.g. on github.

***Important note to software developers:*** Datalab is not an Integrated Development Environment, it does not integrate well with GIT, it does not allow debuging, code navigation, etc. but it is perfect tool for presenting your ideas and prototyping!

Notebook is composed of input cells where you can enter your code and execute it. Results like printouts, charts, etc. are displayed below the input cell and above the next input cell (if it has been created). Your code can be organized in independently executed cells, but variables created in one cell are accessible in other cells because all the cells in specific notebook share memory and are executed in the same python process.

Please execute below cells with simple python code to become familiar with these concepts. Select the first one and click 'Run' button in top menu or use keyboard shortcut Shift+Enter. First row will be executed and the next one will be selected automatically. Press 'Run' button or Shift+Enter 3 more times and analyze the results.

In [1]:
x = 5
y = 6

In [2]:
x+y

11

In [3]:
x = 7

In [4]:
print(x+y)

13


Now modify value of x from 7 to 9 in the second to last of the above cells and rerun last 2 cells. The result of last row should change. This demonstrates that you can execute any call at any time and the currect state of objects stored in memory depends on order of cell's execution - this feature is usefull when you are experimenting with your code, adjusting values of parameters, etc.

Other useful keyboard shortcuts are:

    Ctrl + '/' : Comments out selected text

    Ctrl + Shift + '-': Splits selected cell into two, everything on the right hand side of cursor is moved to newly created cell below the current one.

Splitting cell is usefull to separate time consuming sections of code (e.g. downloading 100 MB of data from ftp) from fast in-memory operations on data. Practice it by splitting below cell in such a way, that you can execute line 'analyse_data()' several times without need to execute 'load_data' function more than once.

In [5]:
import time

def load_data():
    print("Loading Data...")
    time.sleep(5)
    print("Completed...")
        
def analyse_data():
    print("Analysed Data...")

load_data()

Loading Data...
Completed...


In [7]:
analyse_data()

Analysed Data...


# 2. Pandas

Allows users to easily read and manipulate data in a tabular format.

Pandas is built on top of the NumPy library and allows for fast analysis and data cleaning and preparation.

Pandas can also work with data from a wide variety of formats/sources

The objects which hold this tabular data are called Dataframes and Dataframes contain Series.


## 2.1 Series

A series are like numpy arrays but with axis labels.
You will probably never really work with Series but to understand Dataframes properly we should know how series operate.

In [8]:
import numpy as np
import pandas as pd
print("imported")

imported


In [9]:
#  lists, dictionarys and numpy arrays can be created as series
labels = ['a','b','c','d']
my_data = [10, 20 ,30, 40]
arr = np.array(my_data)
d = {'a':10,'b':20,'c':30}

### 2.1.1 Create series from my_data variable

In [10]:
series = pd.Series(data = my_data)

Run the below 3 cells in order to see internal structure of the series

In [11]:
series.values

array([10, 20, 30, 40])

In [12]:
series

0    10
1    20
2    30
3    40
dtype: int64

In [13]:
series.index

RangeIndex(start=0, stop=4, step=1)

### 2.1.2 Create series from 'my_data' variable using 'labels' as index

In [14]:
series_with_index = pd.Series(data = my_data, index = labels)


Again, run the below 3 cells in order to see internal structure of the series

In [15]:
series_with_index.values

array([10, 20, 30, 40])

In [16]:
series_with_index

a    10
b    20
c    30
d    40
dtype: int64

In [17]:
series_with_index.index

Index(['a', 'b', 'c', 'd'], dtype='object')

### 2.1.3 Do the same using 'arr' and data and 'labels' as index and store result in 'ser1' variable

In [18]:
ser1 = pd.Series(data = arr, index = labels)
ser1

a    10
b    20
c    30
d    40
dtype: int64

### 2.1.4 Do the same using dict 'd' and store result in 'ser2' variable

In [19]:
ser2 = pd.Series(data = d)

In [20]:
ser1

a    10
b    20
c    30
d    40
dtype: int64

In [21]:
ser2

a    10
b    20
c    30
dtype: int64

### 2.1.5 print row with index = 'a'

In [22]:
ser1['a']

10

### 2.1.6 Add ser1 to ser2

In [23]:
ser1 + ser2

a    20.0
b    40.0
c    60.0
d     NaN
dtype: float64

## 2.2 DataFrames

In [24]:
my_data = np.random.randn(4,4)

df = pd.DataFrame(my_data,['A','B','C','D'],['A','B','C','D'])
df

A         B         C         D
A  1.231968 -1.329149 -1.736254  0.821825
B -0.580886 -1.652873 -0.940040 -0.269720
C -0.005393  0.107493 -2.183839 -0.658863
D -2.534953 -0.469081 -0.554237 -0.896173

Get list of columns in dataframe

In [25]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

### 2.2.1 Access column A

In [26]:
df['A']

A    1.231968
B   -0.580886
C   -0.005393
D   -2.534953
Name: A, dtype: float64

What exactly is a column?

In [27]:
type(df['A'])

pandas.core.series.Series

### 2.2.2 Access row (index) A

In [28]:
df.loc['A']

A    1.231968
B   -1.329149
C   -1.736254
D    0.821825
Name: A, dtype: float64

What exactly is a row?

In [29]:
type(df.loc['A'])

pandas.core.series.Series

### 2.2.3 Other ways of accessing column(s), row(s) and cell(s)

In [30]:
df.A # equivalent of df['A']

A    1.231968
B   -0.580886
C   -0.005393
D   -2.534953
Name: A, dtype: float64

In [31]:
df[['A','B']] # select multiple columns

A         B
A  1.231968 -1.329149
B -0.580886 -1.652873
C -0.005393  0.107493
D -2.534953 -0.469081

In [32]:
df.iloc[:,2:4] # select multiple columns by integer indexes

C         D
A -1.736254  0.821825
B -0.940040 -0.269720
C -2.183839 -0.658863
D -0.554237 -0.896173

In [33]:
df.loc[['A','B']] # select multiple rows

A         B         C         D
A  1.231968 -1.329149 -1.736254  0.821825
B -0.580886 -1.652873 -0.940040 -0.269720

In [34]:
df.iloc[2:4] # select multiple rows by integer indexes

A         B         C         D
C -0.005393  0.107493 -2.183839 -0.658863
D -2.534953 -0.469081 -0.554237 -0.896173

In [35]:
df[2:4] # CAUTION: slicing with indexing operator filters rows!

A         B         C         D
C -0.005393  0.107493 -2.183839 -0.658863
D -2.534953 -0.469081 -0.554237 -0.896173

In [36]:
df.loc['B','A'] # select value of cell in row B and column A

-0.5808855625032685

In [37]:
df.loc[['B','A'],['C','A']] # select multiple cells

C         A
B -0.940040 -0.580886
A -1.736254  1.231968

In [38]:
df.iloc[1,2] # select value of cell in specific row and column using integer indexes

-0.9400397732846094

In [39]:
df.iloc[2:4,1:3] # select multiple cells in specific rows and columns using integer indexes

B         C
C  0.107493 -2.183839
D -0.469081 -0.554237

### 2.2.4 Adding column to dataframe

In [40]:
df['new'] = df['A'] + df['B']
df

A         B         C         D       new
A  1.231968 -1.329149 -1.736254  0.821825 -0.097181
B -0.580886 -1.652873 -0.940040 -0.269720 -2.233758
C -0.005393  0.107493 -2.183839 -0.658863  0.102100
D -2.534953 -0.469081 -0.554237 -0.896173 -3.004034

### 2.2.5 Dropping rows (default behavious is to returns new dataframe)

In [41]:
df.drop(['A'])

A         B         C         D       new
B -0.580886 -1.652873 -0.940040 -0.269720 -2.233758
C -0.005393  0.107493 -2.183839 -0.658863  0.102100
D -2.534953 -0.469081 -0.554237 -0.896173 -3.004034

In [42]:
df

A         B         C         D       new
A  1.231968 -1.329149 -1.736254  0.821825 -0.097181
B -0.580886 -1.652873 -0.940040 -0.269720 -2.233758
C -0.005393  0.107493 -2.183839 -0.658863  0.102100
D -2.534953 -0.469081 -0.554237 -0.896173 -3.004034

### 2.2.6 Dropping columns (default behavious is to returns new dataframe)

In [43]:
df.drop(['A'], axis = 1) #note axis kwarg

B         C         D       new
A -1.329149 -1.736254  0.821825 -0.097181
B -1.652873 -0.940040 -0.269720 -2.233758
C  0.107493 -2.183839 -0.658863  0.102100
D -0.469081 -0.554237 -0.896173 -3.004034

### 2.3 Filtering

In [44]:
#Check which cells satisfy a condition
print(df)
df > 0

          A         B         C         D       new
A  1.231968 -1.329149 -1.736254  0.821825 -0.097181
B -0.580886 -1.652873 -0.940040 -0.269720 -2.233758
C -0.005393  0.107493 -2.183839 -0.658863  0.102100
D -2.534953 -0.469081 -0.554237 -0.896173 -3.004034


A      B      C      D    new
A   True  False  False   True  False
B  False  False  False  False  False
C  False   True  False  False   True
D  False  False  False  False  False

In [45]:
#Print values of cells satisfy a condition
df[df>0]

A         B   C         D     new
A  1.231968       NaN NaN  0.821825     NaN
B       NaN       NaN NaN       NaN     NaN
C       NaN  0.107493 NaN       NaN  0.1021
D       NaN       NaN NaN       NaN     NaN

In [46]:
#Print values of cells satisfy a condition with remaining cells replaced with zeros
df[df>0].fillna(0)

A         B    C         D     new
A  1.231968  0.000000  0.0  0.821825  0.0000
B  0.000000  0.000000  0.0  0.000000  0.0000
C  0.000000  0.107493  0.0  0.000000  0.1021
D  0.000000  0.000000  0.0  0.000000  0.0000

In [47]:
#applying condition to single column returns Series of True/False values
df['C']>0

A    False
B    False
C    False
D    False
Name: C, dtype: bool

In [48]:
#Select rows where C > 0
df[df['C']>0]

Empty DataFrame
Columns: [A, B, C, D, new]
Index: []

In [49]:
#becaue a dataframe is returned you can process is further

df[df['C']>0]['new'] #select values in 'new' columns where C > 0 

Series([], Name: new, dtype: float64)

In [50]:
#multiple conidtions (remember to surround each subcondition with brackets!)

df[ (df['C']>0) & (df['A']>0) ] #AND

Empty DataFrame
Columns: [A, B, C, D, new]
Index: []

In [51]:
df[(df['C']>0) | (df['B']>0) ] #OR

A         B         C         D     new
C -0.005393  0.107493 -2.183839 -0.658863  0.1021

## 2.4 Operations

In [52]:
df = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xhz']})

df

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xhz

### 2.4.1 Get top n rows

In [53]:
df.head(2)

col1  col2 col3
0     1   444  abc
1     2   555  def

### 2.4.2 Get unique values in a column

In [54]:
df['col2'].unique()

array([444, 555, 666])

### 2.4.3 Get number of unique values in a column

In [55]:
df['col2'].nunique()

3

### 2.4.4 Get number of occurrences of unique values in a column

In [56]:
df['col2'].value_counts()

444    2
555    1
666    1
Name: col2, dtype: int64

### 2.4.5 Get some statistics for the column

In [57]:
df['col1'].sum()

10

In [58]:
df['col1'].mean()

2.5

In [59]:
df['col1'].describe()

count    4.000000
mean     2.500000
std      1.290994
min      1.000000
25%      1.750000
50%      2.500000
75%      3.250000
max      4.000000
Name: col1, dtype: float64

### 2.4.6 Use values in columns in complex computations

In [60]:
def times2(x):
    return x * 2

In [61]:
df['col1'].apply(times2) # this will execute function times2 for each row in column col1

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [62]:
df['col1'].apply(lambda x: x *2) # one can do the same using lambda expression...

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [63]:
df['col1'] * 2 # or just multiply column by 2

0    2
1    4
2    6
3    8
Name: col1, dtype: int64

In [64]:
np.log(df['col1']) # Pandas Series can be passed to math function provided by numpy 

0    0.000000
1    0.693147
2    1.098612
3    1.386294
Name: col1, dtype: float64

## 2.5 Working with multiple DataFrames

### 2.5.1 Concatenation (a.k.a. UNION)

In [65]:
df1 = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xhz']})

df2 = pd.DataFrame({'col1':[5,6,7,8],
                   'col2':[111,222,333,888],
                   'col3':['abc','def','ghi','xhz']})

In [66]:
df1

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xhz

In [67]:
df2

col1  col2 col3
0     5   111  abc
1     6   222  def
2     7   333  ghi
3     8   888  xhz

In [68]:
pd.concat([df1,df2])

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xhz
0     5   111  abc
1     6   222  def
2     7   333  ghi
3     8   888  xhz

### 2.5.2 Merging (a.k.a. JOIN on columns)

In [69]:
df1 = pd.DataFrame({'col1':[1,2,3,4],
                   'col2':[444,555,666,444],
                   'col3':['abc','def','ghi','xhz']})

df2 = pd.DataFrame({'col1':[1,6,3,8],
                   'col4':[111,222,333,888],
                   'col5':['abc','def','ghi','xhz']})

In [70]:
df1

col1  col2 col3
0     1   444  abc
1     2   555  def
2     3   666  ghi
3     4   444  xhz

In [71]:
df2

col1  col4 col5
0     1   111  abc
1     6   222  def
2     3   333  ghi
3     8   888  xhz

In [72]:
df1.merge(df2, on='col1')

col1  col2 col3  col4 col5
0     1   444  abc   111  abc
1     3   666  ghi   333  ghi

### 2.5.3 Joining (a.k.a. JOIN on indices)

In [73]:
df1_indexed = df1.set_index('col1')

In [74]:
df1_indexed

col2 col3
col1           
1      444  abc
2      555  def
3      666  ghi
4      444  xhz

In [75]:
df2_indexed = df2.set_index('col1')

In [76]:
df2_indexed

col4 col5
col1           
1      111  abc
6      222  def
3      333  ghi
8      888  xhz

In [77]:
df1_indexed.join(df2_indexed)

col2 col3   col4 col5
col1                       
1      444  abc  111.0  abc
2      555  def    NaN  NaN
3      666  ghi  333.0  ghi
4      444  xhz    NaN  NaN

In [78]:
df1_indexed.join(df2_indexed)

col2 col3   col4 col5
col1                       
1      444  abc  111.0  abc
2      555  def    NaN  NaN
3      666  ghi  333.0  ghi
4      444  xhz    NaN  NaN

In [80]:
df1_indexed.join(df1_indexed, rsuffix = 'r')

col2 col3  col2r col3r
col1                        
1      444  abc    444   abc
2      555  def    555   def
3      666  ghi    666   ghi
4      444  xhz    444   xhz